### PR TITLE
Front padding bug

### LINKED ISSUE #165: Director shot movement to 0 with front padding
When moving a DirectorShot to start at count 0, and it has front padding > 0, its camera blocks will not be moved (because exceptions are thrown). This should be handled gracefully. The best way is probably to not allow this movement.

### PR DESCRIPTION
**Pull request by mennoo1996**
Fixes #165 
Also added padding to director timetable block

### CODE REVIEW

File: src/main/java/control/DirectorTimelineController.java [hunk 1]
```diff
@@ -134,6 +142,7 @@ public void shotChangedHandler(DirectorShotBlockUpdatedEvent event) {
 
         // check for collisions
         checkCollisions(changedBlock);
+
```
Comment (Markvanderuit) [inline src/main/java/control/DirectorTimelineController.java:145]: Hi, unnecessary whitespace.

**Comment by Markvanderuit** [comment]
Looks good. I'll let a second member review it before merging.

**Comment by bart-de-jonge** [comment]
Looks good to me, please fix the whitespace
