### PR TITLE
Issue fixes

### LINKED ISSUE #210: Edit instruments in DirectorShots
The button or menu for this is missing.

### PR DESCRIPTION
**Pull request by mennoo1996**
Fixes #210, #211

### CODE REVIEW

File: src/main/java/control/DetailViewController.java [hunk 1]
```diff
@@ -591,6 +592,7 @@ private void cameraDropdownListenerHelper(StyledMenuButton buttons) {
      * @param buttons the dropdown menu containing buttons.
      */
     private void instrumentsDropdownListenerHelper(StyledMenuButton buttons) {
+        System.out.println("IS THIS CALLED?");
```
Comment (geenen124) [inline src/main/java/control/DetailViewController.java]: Remove print statements

**Comment by geenen124** [comment]
Nice work!

**Comment by Markvanderuit** [comment]
Looks good, I'll merge.
