### PR TITLE
Issue fixes

### LINKED ISSUE #178: Director shot collision
When seperating two colliding director shots, they stay highlighted red, until you move them once more.

### PR DESCRIPTION
**Pull request by mennoo1996**
Fixes #178, #195, #196, #197, #198, #199, #200 
Director shot collision now updates appropriately
Camera shots are not linked anymore when created together
On application start, the changed boolean is now correctly set to false
Collisions are updated appropriately when creating camera shots via DirectorDetailView
Director shots are not deleted anymore when deleting a camera shot via detail view
You can now create director shots with 0 camera shots
Text in a text field is auto selected on focus.

### CODE REVIEW

**Comment by bart-de-jonge** [comment]
Looks fine to me!

File: src/main/java/gui/modal/EditProjectModalView.java [hunk 1]
```diff
@@ -178,7 +179,7 @@ public EditProjectModalView(RootPane rootPane,
         }
         initializeView();
     }
-
```
Comment (Markvanderuit) [inline src/main/java/gui/modal/EditProjectModalView.java:181]: Wow.

**Comment by Markvanderuit** [comment]
Looks good. Second member can merge.
